### ISSUE TITLE
Different Results than reported

### ISSUE THREAD

**Issue by shivangibithel** [zhixiongz/CLIP4CMR#1]
Hey @zhixiongz 

I like your work and tried to reproduce the numbers on the Nuswide dataset for the different losses. 
In line 169 in main.py you used betas as a variable and haven't initialized it anywhere. I kept the default values of beta for adam optimizer to generate results. My results are different and lower from the values reported in Table2. 

https://github.com/zhixiongz/CLIP4CMR/blob/ca75cfccc3486263b0d5f116cf546798cf31f572/main.py#L169

Please update the code for the values that you used to generate the numbers in Table 2.  

Thanks and Regards
Shivangi

**Comment by zhixiongz** [comment]
Hey @shivangibithel 

Thanks a lot for your suggestion, we have updated the default values in main.py. The results reported in Table 2 on the NUS-WIDE dataset only use 1000 test samples, as with previous baseline methods, I guess you probably used the full 2000 test samples in test.pkl. Since mAP is evaluated on the entire test set, more test samples lead to poorer results. Here we use the common dataset partition provided by [Corr-AE](https://dl.acm.org/doi/10.1145/2647868.2654902).

We have updated the test data of NUS-WIDE in the cloud storage, please see https://pan.cstcloud.cn/s/JqKbqGfTRs

**Comment by shivangibithel** [comment]
Hey @zhixiongz 

Thank you for the update. 
Please give some information about how you created train.pkl and test.pkl and it would be really helpful if you could upload the script for that too with some reference dataset having a folder with images and a file with captions.
I loaded the files and printed them to the screen to know the data type,  the text is not simply in the tokenized format, and labels are encoded as well. Also the ids seem to be randomly generated as in the figure. 


![image](https://user-images.githubusercontent.com/19774925/149622907-53c9b95a-78bd-42f7-944a-8997201cb819.png)

I want to create the train.pkl and test.pkl for other custom datasets.

Thanks in advance.
 
Regards
Shivangi
